# Generated by Django 4.2 on 2023-04-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RemovalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
